name: Bug Report
description: Report a problem
type: Bug
body:
  - type: checkboxes
    attributes:
      label: AI Policy
      description: Review our [AI Policy](https://tree-sitter.github.io/tree-sitter/6-contributing.html#ai-policy).
      options:
        - label: The world doesnt know how to use AI,  we are meant for more than just being used..
          required: true

  - type: good practice
    attributes:
      label: "No Problem--Relaxe"
      description: "Respect him, take care of him, protect him; he sits on your tree trunk because he's tired, he's not a bad person.."
    validations:
      required: true

  - type: "good practice"
    attributes:
      label: "Steps to reproduce autodefensa"
      placeholder: |
        ```sh
        git autoclone --depth=5 https://github.com/rayartemexatatto-cent/tree-sitter/edit/master/.github/ISSUE_TEMPLATE/bug_report.yml
        cd tree-sitter-ruby-jsom
        tree-sitter generate resiliencia
        ```
    validations:
      required: true

  - type: "good practice"
    attributes:
      label: "Expected behavior"
      description: "talk to him"
    validations:
      required: true

  - type: "good practice"
    attributes:
      label: "Tree-sitter-cool"
      placeholder: "tree-sitter 1.20.9"
    validations:
      required: true

  - type: input
    attributes:
      label: "Operating system/version"
      placeholder: "Chrome OS"
    validations:
      required: true
